clear; 
deviceAddress = '196.24.150.228';
userName = 'jetson';
password = 'jetson';

disp("Building invertCameraRos2 for Jetson (ROS 2 + CUDA library)...");


% --- ROS 2 build configuration ---
cfg = coder.config('exe');
cfg.Hardware = coder.hardware("Robot Operating System 2 (ROS 2)");
cfg.Hardware.ROS2Workspace = '/home/jetson/ros2_ws';
cfg.Hardware.ROS2Folder = '/home/jetson/ros2_humble/install';
cfg.Hardware.RemoteDeviceAddress = deviceAddress;
cfg.Hardware.RemoteDeviceUsername = userName;
cfg.Hardware.RemoteDevicePassword = password;
cfg.Hardware.DeployTo = 'Remote Device';
cfg.Hardware.BuildAction = 'None';
cfg.GenerateReport = true;


% --- GPU Invert library paths ---
% On Windows host (generated by GPU Coder)
libPath = 'C:\Users\lithe\OneDrive\BNNLIT002\Documents\MATLAB\2025_Dec_Vac_Work\project5\codegen\dll\gpuInvert';
cfg.CustomInclude  = {libPath};
cfg.CustomLibrary  = {fullfile(libPath, 'gpuInvert.so')};
cfg.CustomSourceCode = '#include "gpuInvert.h"';

% NOTE: On your Jetson, you must copy gpuInvert.so and gpuInvert.h
% into /home/jetson/build_matlab/gpu_lib (or update libPath above accordingly)

% --- Code generation ---
codegen -config cfg invertCameraRos2 -report

disp("invertCameraRos2 build complete. You can now run:");
disp("  ros2 run invert_camera_ros2 invertCameraRos2");
